In [ ]:
#Q1. What are the benefits of the built-in array package, if any?

"""As of my knowledge cutoff in September 2021, the Python programming language does not have a built-in array package. 
   However, Python does have a built-in data structure called a list, which can be used to store a collection of elements. 
   Lists in Python provide several benefits, including:

   Dynamic size: Lists in Python can grow or shrink dynamically. You can add or remove elements from a list easily, making it
   flexible for various use cases.

   Versatility: Lists can store different types of objects such as numbers, strings, or even other lists. This versatility 
   allows you to create complex data structures and manipulate them effectively.

   Indexing and slicing: You can access individual elements in a list using their index positions. This enables you to 
   retrieve, modify, or delete specific elements efficiently. Additionally, lists support slicing, which allows you to 
   extract sublists based on specified ranges.

   Iteration: Lists can be iterated over using loops, making it convenient to perform operations on each element of the list.

   Built-in methods: Python provides a range of built-in methods for lists, such as append(), remove(), sort(), and reverse(). 
   These methods offer convenient ways to add, remove, or manipulate elements within a list.

   It's worth noting that there are additional packages and libraries in Python, such as NumPy, that provide optimized arrays 
   for numerical computations. NumPy arrays offer benefits like efficient element-wise operations, mathematical functions, and 
   advanced indexing capabilities. However, these are not built-in to Python and require separate installation."""

#Q2. What are some of the array package&'s limitations?

"""If you are referring to the limitations of the NumPy array package, which is commonly used for numerical computations in 
   Python, here are some of its limitations:

   1. Homogeneous data types: NumPy arrays require elements to have the same data type. Unlike Python lists, which can
      accommodate different types of objects in a single list, NumPy arrays enforce uniformity. This can be restrictive
      when dealing with heterogeneous data.

   2. Fixed size: NumPy arrays have a fixed size upon creation. Once an array is created, its size cannot be changed.
      If you need to add or remove elements, you would have to create a new array and copy the data, which can be inefficient 
      for large arrays.

   3. Reshaping arrays: While NumPy provides functions to reshape arrays, the reshaping process requires careful consideration
      of the dimensions and sizes of the array. In some cases, reshaping arrays can result in creating copies of the data,
      which can consume additional memory.

   4. Slower execution for certain operations: NumPy arrays can be slower for certain operations compared to specialized
      libraries implemented in lower-level languages, such as C or Fortran. However, NumPy usually provides a good balance
      between performance and ease of use for most numerical computations.

   5. Lack of support for parallel processing: NumPy operations typically run sequentially on a single core of the CPU. 
      Although you can utilize vectorized operations for efficient computations, NumPy does not inherently support parallel
      processing on multiple cores or distributed computing. To achieve parallelism, you would need to use other libraries 
      or frameworks built on top of NumPy, such as Dask or PyTorch.

 Despite these limitations, NumPy remains a powerful and widely used package for array manipulation and numerical computations
 in Python due to its performance, rich functionality, and integration with other scientific computing libraries."""

#Q3. Describe the main differences between the array and numpy packages.

"""The main differences between the array and numpy packages are as follows:

   1. Functionality: The array package provides basic array operations and functionality, whereas the numpy package expands
      on this and provides a comprehensive set of tools for working with arrays, including advanced mathematical functions,
      linear algebra operations, Fourier transforms, and more. Numpy is built on top of the array package and extends its 
      capabilities.

   2. Performance: Numpy is highly optimized for numerical operations and is generally faster than the array package. 
      Numpy utilizes efficient algorithms and data structures implemented in C, which makes it more suitable for handling 
      large datasets and performing complex computations. In contrast, the array package may be slower for certain operations 
      due to its more limited functionality and implementation.

   3. Syntax and Usage: The array package uses a simpler syntax compared to numpy. It provides a basic set of array operations
      and relies on Python's built-in functionality. Numpy, on the other hand, introduces a new array object called ndarray
      (N-dimensional array) and provides a wide range of methods and functions specifically designed for working with these
      arrays. Numpy's syntax is more concise and allows for more efficient and readable code.

   4. Ecosystem and Community: Numpy has a large and active community of users and developers, which means there are extensive
      resources available, such as documentation, tutorials, and community support. It is widely used in scientific computing,
      data analysis, and machine learning. The array package, being a simpler package, does not have the same level of 
      community and ecosystem as numpy.

 In summary, while the array package provides basic array functionality, numpy is a more comprehensive and powerful package
 for array manipulation and numerical operations. Numpy offers better performance, a wider range of functions, and a larger
 community of users and developers, making it the preferred choice for most scientific computing and data analysis tasks."""

#Q4. Explain the distinctions between the empty, ones, and zeros functions.

"""The empty, ones, and zeros functions are all used to create arrays in numpy, but they have different behaviors and purposes.
   Here are the distinctions between these functions:

  1. empty():
     The numpy.empty() function creates an array without initializing its elements to any particular values. It simply
    allocates the memory space for the array. The elements of the array created by empty() will contain whatever values
    were already present in that memory location, which can be random and unpredictable. Therefore, the values of the
    elements in an empty array are undefined and can vary each time you create an empty array. It is primarily used when 
    you want to allocate an array of a specific size without initializing its values explicitly.
    
 Example:
 import numpy as np
 arr = np.empty((2, 2))
 print(arr)
 
 Output:
 [[6.94841746e-310 6.94841746e-310]
 [1.48219694e-323 0.00000000e+000]]


  2. ones():
     The numpy.ones() function creates a new array and initializes all its elements to the value 1. It takes the desired shape
     of the array as input and returns an array of that shape filled with ones. It is commonly used when you need to create an
     array of ones for various numerical computations or as an initial placeholder.
     
  Example:
  import numpy as np
  arr = np.ones((2, 3))
  print(arr)
  
  Output:
  [[1. 1. 1.]
  [1. 1. 1.]]
  
  
  3. zeros():
     The numpy.zeros() function creates a new array and initializes all its elements to the value 0. It takes the desired shape
     of the array as input and returns an array of that shape filled with zeros. Similar to the ones() function, it is 
     frequently used when you want to create an array of zeros for numerical operations or as an initial placeholder.
     
  Example:
  import numpy as np
  arr = np.zeros((3, 2))
  print(arr)
  
  Output:
  [[0. 0.]
 [0. 0.]
 [0. 0.]]
 
 In summary, the empty() function creates an array without initializing its values, ones() creates an array filled with ones, 
 and zeros() creates an array filled with zeros. These functions are useful for different scenarios depending on whether you
 need an array with undefined values, an array with all elements set to one, or an array with all elements set to zero."""

#Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

"""In the numpy.fromfunction() function, the callable argument refers to a function or callable object that is used to
   generate the values for the elements of the new array being constructed. The fromfunction() function allows you to 
   create an array by applying a specified function to the indices of the array.

   The general syntax of numpy.fromfunction() is as follows:
   
   numpy.fromfunction(function, shape, **kwargs)
   
   . function: This argument is a callable object that defines the operation to be applied to the indices of the array. 
     The function takes as input the indices of the array and returns the corresponding value for each element. The indices 
     are provided as separate arguments for each dimension of the array. For example, if you have a 2-dimensional array, the
     function should accept two arguments representing the row and column indices.

   . shape: This argument specifies the shape of the output array, defining the dimensions of the array to be created.

   . **kwargs: Additional keyword arguments that can be passed to the function, which can affect the behavior of the function 
     or provide extra parameters.
     
  The callable function is called with the indices of each element of the new array being constructed, based on the specified 
  shape. The function is called for each element of the array, and the returned values are used to populate the corresponding 
  elements.

  Here's an example to illustrate the usage of numpy.fromfunction(): 
  
  import numpy as np

def my_function(i, j):
    return 2 * i + j

arr = np.fromfunction(my_function, (3, 4))
print(arr)

  Output:
  [[0. 1. 2. 3.]
 [2. 3. 4. 5.]
 [4. 5. 6. 7.]]
 
  In this example, the my_function() function takes two arguments, i and j, representing the row and column indices. It returns
  the value 2 * i + j. The fromfunction() function uses this function to generate the values for each element of the new array 
  with a shape of (3, 4). The resulting array is populated with the values returned by the function for each index combination.

  So, the callable argument in numpy.fromfunction() plays a crucial role in determining the values of the elements in the new
  array by applying a function to the indices of the array."""

#Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point
value) through addition, as in the expression A + n?

"""When a numpy array is combined with a single-value operand (a scalar) through addition, such as in the expression A + n,
   numpy performs an element-wise addition between the array elements and the scalar value. This operation is applied to each 
   element of the array, where the scalar value is added to each element individually.

   The scalar value is broadcasted to match the shape of the array, if necessary, to ensure the dimensions are compatible for
   element-wise addition. Broadcasting is a concept in numpy that allows arrays with different shapes to be operated together.

   Here's an example to demonstrate the element-wise addition between a numpy array and a scalar:
   
   import numpy as np

  A = np.array([1, 2, 3, 4])
  n = 5

  result = A + n

  print(result)
  
  Output:
  [6 7 8 9]
  
  In this example, the scalar value n (which is 5) is added to each element of the numpy array A. The result is a new numpy
  array where each element of A has been incremented by the value of n.

  The broadcasting rules in numpy allow for more complex scenarios, where arrays with different shapes can be combined with
  scalar values. For example, if you have a 2D array, broadcasting will adjust the scalar value to match the shape of the 
  array, enabling element-wise addition.

  It's important to note that the original numpy array A remains unchanged, and the result of the addition is a new numpy
  array. If you wish to modify the original array in-place, you can use the += operator, like A += n."""

#Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

"""No, array-to-scalar operations cannot use combined operation-assign operators (such as += or *=). If you try to perform
   such operations, a TypeError will be raised.

   The combined operation-assign operators are designed for in-place modification of arrays, where the operation is performed
   between two arrays and the result is stored back into the original array. However, when combining an array with a scalar
   value, the array-to-scalar operation does not support in-place modification.

  Here's an example to illustrate this:
  
  import numpy as np

  A = np.array([1, 2, 3, 4])
  n = 5

  A += n  # Trying to perform in-place addition

  print(A)
  
  Output:
  TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
  
  In this example, the += operator is used to perform in-place addition of the scalar n to each element of the array A. 
  However, it raises a TypeError because numpy tries to cast the result of the addition (which is a float) back to the 
  integer dtype of A, which is not allowed by the casting rules.

  To perform such operations between an array and a scalar, you can use the regular arithmetic operators (+, -, *, /)
  without the combined operation-assign operators. This will create a new array with the result of the operation.

  If you want to modify the original array in-place, you can use the regular assignment operator (=) to assign the result 
  of the operation back to the original array, like A = A + n or A = A * n."""

#Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

"""Yes, a numpy array can contain fixed-length strings using the dtype parameter. You can specify a fixed-length string type
   using the numpy.string_ or numpy.str_ data types, along with a specified length for the strings.

   When you allocate a longer string to a fixed-length string array, numpy will automatically truncate the string to fit within
   the specified length. It will not raise an error or exception; instead, it silently truncates the string to fit the 
   allocated space.

  Here's an example to illustrate this behavior:
  
  import numpy as np

# Creating a fixed-length string array of length 5
arr = np.array(['apple', 'banana', 'cherry'], dtype=np.string_, length=5)

# Assigning a longer string to one of the elements
arr[1] = 'pineapple'

print(arr)

 Output:
 [b'apple' b'pinea' b'cherr']
 
 In this example, we create a numpy array arr with a fixed-length string of 5 characters using the np.string_ data type and
 specifying a length of 5. Then, we assign the string 'pineapple' to the second element of the array. However, since the
 length of 'pineapple' is longer than the allocated space of 5 characters, numpy truncates the string to fit within the
 specified length. The resulting array shows the truncated strings: 'apple', 'pinea', and 'cherr'.

 It's important to note that when you allocate a longer string to a fixed-length string array, the truncation occurs silently 
 without any warning or error. Therefore, it's necessary to ensure that the assigned strings fit within the specified length 
 to avoid unintended truncation."""

#Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the 
conditions for combining two numpy arrays?

"""When you combine two numpy arrays using an operation like addition (+) or multiplication (*), numpy performs element-wise 
   operations between the corresponding elements of the arrays. The resulting array will have the same shape as the input
   arrays, and the operation is applied to each pair of corresponding elements.

   To combine two numpy arrays, the following conditions should be met:

   1. The arrays should have compatible shapes. This means that the dimensions of the arrays should match or be broadcastable.
      Broadcasting is a mechanism in numpy that allows arrays with different shapes to be operated together. Arrays with 
      different shapes can be broadcasted to a common shape before performing element-wise operations.

   2. The arrays should have compatible data types. The data types of the arrays should be compatible for the specified 
      operation. For example, addition or multiplication between arrays requires compatible numerical data types.

  Here are some examples to illustrate array combination using addition and multiplication:
  
  import numpy as np

# Addition
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_addition = arr1 + arr2
print(result_addition)
# Output: [5 7 9]

# Multiplication
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])
result_multiplication = arr3 * arr4
print(result_multiplication)
# Output: [4 10 18]

 In these examples, the arrays arr1 and arr2 have the same shape, so the addition operation is performed element-wise,
 resulting in a new array with the same shape as the input arrays. Similarly, the arrays arr3 and arr4 have the same shape,
 so the multiplication operation is performed element-wise, resulting in a new array with the same shape.

  If the arrays have different shapes, numpy will try to broadcast them to a common shape if possible. If broadcasting is not 
  possible due to incompatible shapes, numpy will raise a ValueError indicating the shape incompatibility.

  It's important to note that when combining arrays, the original arrays remain unchanged, and the result of the operation is
  a new numpy array. If you want to modify one of the original arrays in-place, you can use combined operation-assign operators
  like += or *=."""

#Q10. What is the best way to use a Boolean array to mask another array?

"""The best way to use a Boolean array to mask another array in numpy is by applying the Boolean array as an indexing mask.
   Numpy provides the capability to use a Boolean array to select specific elements from another array based on the 
   corresponding Boolean values.

   Here's an example to demonstrate the process:
   
   import numpy as np

# Create a Boolean array as a mask
mask = np.array([True, False, True, False])

# Create an array to be masked
arr = np.array([1, 2, 3, 4])

# Use the mask to select elements from the array
masked_arr = arr[mask]

print(masked_arr)

 Output:
 [1 3]

 In this example, we have a Boolean array mask and an array arr. The mask selects elements from arr where the corresponding 
 value in mask is True. The resulting masked array, masked_arr, only contains the elements from arr that correspond to the
 True values in mask.

 You can use this masking technique to perform various operations on arrays, such as filtering, selecting specific elements,
 or assigning new values to specific elements.

 Additionally, you can also use the np.where() function to achieve similar results. The np.where() function returns elements
 from one array where the corresponding Boolean condition is True and returns elements from another array where the condition 
 is False.

 Here's an example using np.where():
 
 import numpy as np

# Create a Boolean array as a mask
mask = np.array([True, False, True, False])

# Create arrays for true_values and false_values
true_values = np.array([10, 20, 30, 40])
false_values = np.array([-1, -2, -3, -4])

# Use np.where() to select elements based on the mask
result = np.where(mask, true_values, false_values)

print(result)

 Output:
 [10 -2 30 -4]
 
 In this example, we use the np.where() function to select elements from true_values when the corresponding value in mask is
 True, and elements from false_values when the corresponding value in mask is False.

 Both using a Boolean array as an indexing mask and using np.where() are effective methods to mask or select elements from
 another array based on Boolean conditions, depending on your specific requirements."""

#Q11. What are three different ways to get the standard deviation of a wide collection of data using
both standard Python and its packages? Sort the three of them by how quickly they execute.

"""Here are three different ways to calculate the standard deviation of a wide collection of data using standard Python and its
   packages, sorted by their execution speed from fastest to slowest:

  1. NumPy:
     
  import numpy as np

  data = np.array([1, 2, 3, 4, 5])  # Replace with your data

  std_dev = np.std(data)
  
 2. NumPy provides the numpy.std() function, which calculates the standard deviation of an array. It is generally the fastest
    method for large collections of data as NumPy is optimized for numerical computations.

 statistics module (Standard Python library):
 import statistics

 data = [1, 2, 3, 4, 5]  # Replace with your data

 std_dev = statistics.stdev(data)

 The statistics module in the standard Python library includes the statistics.stdev() function, which computes the 
 standard deviation of a dataset. This method is generally slower than NumPy but provides the advantage of being part 
 of the standard library.

 3. Math module (Standard Python library):
    import math

  data = [1, 2, 3, 4, 5]  # Replace with your data

 mean = sum(data) / len(data)
 variance = sum((x - mean) ** 2 for x in data) / len(data)
 std_dev = math.sqrt(variance)
 
 The math module in the standard Python library does not provide a direct function for calculating the standard deviation.
 Instead, you can calculate it manually by first computing the variance using the mean and then taking the square root of 
 the variance. This approach is slower than the other two methods, especially for larger datasets, as it involves manual
 calculations.

 In terms of execution speed, NumPy (numpy.std()) is generally the fastest option, followed by the statistics.stdev() function
 from the statistics module, and finally, the manual calculation using the math module. NumPy is specifically designed for 
 numerical computations and takes advantage of optimized algorithms and efficient data structures, making it the most efficient 
 option for large datasets."""

#12. What is the dimensionality of a Boolean mask-generated array?

"""The dimensionality of a Boolean mask-generated array is the same as the dimensionality of the original array that was used
   to create the mask.

   When you use a Boolean mask to select elements from an array, the resulting masked array will have the same number of 
   dimensions as the original array, but it may have a different shape depending on the number of elements selected.

   For example, consider the following code snippet:
   
   import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mask = arr > 5
masked_arr = arr[mask]

print(masked_arr)
print(masked_arr.shape)

  Output:
  [6 7 8 9]
  (4,)
  
  In this example, the original array arr is a 2-dimensional array of shape (3, 3). We create a Boolean mask mask by applying 
  the condition arr > 5, which results in a mask with the same shape as arr. Then, we use the mask to select elements from arr,
  resulting in a 1-dimensional masked array masked_arr containing the elements greater than 5.

  The dimensionality of masked_arr is still 2 (since arr is 2-dimensional), but the shape is different because only certain
  elements from arr were selected based on the mask. In this case, masked_arr has a shape of (4,), indicating that it is a
  1-dimensional array with 4 elements.

  To summarize, the dimensionality of a Boolean mask-generated array remains the same as the original array, while the shape
  may change depending on the number of elements selected by the mask."""